get:
  summary: Obtener lista de artículos con búsqueda opcional
  tags:
    - Artículos
  security:
    - cookieAuth: []
  parameters:
    - in: query
      name: search
      schema:
        type: string
      description: Término de búsqueda para desArticulo o idArticulo.
    - in: query
      name: limit
      schema:
        type: integer
        default: 50
        minimum: 1
        maximum: 100
      description: Número máximo de artículos a devolver.
    - in: query
      name: offset
      schema:
        type: integer
        default: 0
        minimum: 0
      description: Número de artículos a omitir.
  responses:
    '200':
      description: Lista de artículos recuperada exitosamente
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/ProductResponse.yaml'
    '401':
      description: No autorizado / Usuario sin permisos
      content:
        application/json:
          schema:
            $ref: '../schemas/ErrorResponse.yaml'
    '500':
      description: Error interno del servidor
      content:
        application/json:
          schema:
            $ref: '../schemas/ErrorResponse.yaml'
