import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { palletsPosiciones, palletsProductos } from './schema'; // Importar palletsProductos
import { sql } from 'drizzle-orm';
import { env } from '../lib/config';
import { seedEmpresas } from './seedEmpresas'; // Importar seedEmpresas

const pool = new Pool({
  connectionString: env.DATABASE_URL,
});

const db = drizzle(pool, { schema: { palletsPosiciones, palletsProductos } }); // Incluir palletsProductos en el schema

async function seedPalletPositions() {
  console.log('⏳ Seeding pallet positions...');
  try {
    // 1. Limpiar datos existentes
    console.log('🗑️ Clearing old pallet positions data...');
    await db.delete(palletsProductos); // Limpiar productos primero por FK
    await db.execute(sql`ALTER SEQUENCE pallets_productos_id_seq RESTART WITH 1;`);
    await db.delete(palletsPosiciones);
    await db.execute(sql`ALTER SEQUENCE pallets_posiciones_id_seq RESTART WITH 1;`);
    console.log('✅ Old pallet positions data cleared.');

    // 2. Preparar nuevas posiciones
    console.log('📦 Preparing new pallet positions...');
    const positionsToInsert: (typeof palletsPosiciones.$inferInsert)[] = [
      { fila: 'A', posicion: '1.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '2.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '3.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '4.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '5.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '6.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '7.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '8.00', habilitado: false, idEmpresa: 1 },
      { fila: 'A', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '13.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '14.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '15.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '16.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '17.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '18.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '19.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '20.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '21.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '22.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '23.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '24.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '25.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '26.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '27.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '28.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '29.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '30.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '31.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '32.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '33.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '34.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '35.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '36.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '37.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '38.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '39.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '40.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '41.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '42.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '43.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '44.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '45.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '46.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '47.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '48.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '49.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '50.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '51.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '52.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '53.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '54.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '55.00', habilitado: true, idEmpresa: 1 },
      { fila: 'A', posicion: '56.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '1.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '2.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '3.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '4.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '5.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '6.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '7.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '8.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '13.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '14.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '15.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '16.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '17.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '18.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '19.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '20.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '21.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '22.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '23.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '24.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '25.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '26.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '27.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '28.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '29.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '30.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '31.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '32.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '33.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '34.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '35.00', habilitado: true, idEmpresa: 1 },
      { fila: 'B', posicion: '36.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '1.00', habilitado: false, idEmpresa: 1 },
      { fila: 'C', posicion: '2.00', habilitado: false, idEmpresa: 1 },
      { fila: 'C', posicion: '3.00', habilitado: false, idEmpresa: 1 },
      { fila: 'C', posicion: '4.00', habilitado: false, idEmpresa: 1 },
      { fila: 'C', posicion: '5.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '6.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '7.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '8.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '13.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '14.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '15.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '16.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '17.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '18.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '19.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '20.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '21.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '22.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '23.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '24.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '25.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '26.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '27.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '28.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '29.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '30.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '31.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '32.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '33.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '34.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '35.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '36.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '37.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '38.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '39.00', habilitado: true, idEmpresa: 1 },
      { fila: 'C', posicion: '40.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '1.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '2.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '3.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '4.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '5.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '6.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '7.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '8.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '13.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '14.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '15.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '16.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '17.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '18.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '19.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '20.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '21.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '22.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '23.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '24.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '25.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '26.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '27.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '28.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '29.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '30.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '31.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '32.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '33.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '34.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '35.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '36.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '0.10', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '0.20', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '0.30', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '0.40', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '1.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '2.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '3.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '4.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '5.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '6.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '7.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '8.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '13.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '14.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '15.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '16.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '17.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '18.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '19.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '20.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '21.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '22.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '23.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '24.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '25.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '26.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '27.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '28.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '29.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '30.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '31.00', habilitado: true, idEmpresa: 1 },
      { fila: 'E', posicion: '32.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '1.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '2.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '3.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '4.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '5.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '6.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '7.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '8.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'F', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '1.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '2.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '3.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '4.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '5.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '6.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '7.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '8.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '9.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '10.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '11.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '12.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '13.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '14.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '15.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '16.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '17.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '18.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '19.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '20.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '21.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '22.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '23.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '24.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '25.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '26.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '27.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '28.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '29.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '30.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '31.00', habilitado: true, idEmpresa: 1 },
      { fila: 'S', posicion: '32.00', habilitado: true, idEmpresa: 1 },
      { fila: 'D', posicion: '37.00', habilitado: false, idEmpresa: 1 },
      { fila: 'D', posicion: '38.00', habilitado: false, idEmpresa: 1 },
      { fila: 'D', posicion: '39.00', habilitado: false, idEmpresa: 1 },
      { fila: 'D', posicion: '40.00', habilitado: false, idEmpresa: 1 },
      { fila: 'B', posicion: '37.00', habilitado: false, idEmpresa: 1 },
      { fila: 'B', posicion: '38.00', habilitado: false, idEmpresa: 1 },
      { fila: 'B', posicion: '39.00', habilitado: false, idEmpresa: 1 },
      { fila: 'B', posicion: '40.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '33.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '34.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '35.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '36.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '37.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '38.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '39.00', habilitado: false, idEmpresa: 1 },
      { fila: 'E', posicion: '40.00', habilitado: false, idEmpresa: 1 },
    ];

    // 3. Insertar posiciones
    console.log(`➕ Inserting ${positionsToInsert.length} new pallet positions...`);
    await db.insert(palletsPosiciones).values(positionsToInsert);
    console.log('✅ Pallet positions seeded successfully!');
  } catch (error) {
    console.error('❌ Error seeding pallet positions:', error);
    process.exit(1);
  }
}

async function seedPalletProducts() {
  console.log('⏳ Seeding pallet products...');
  try {
    // 1. Preparar nuevos productos de pallet
    console.log('📦 Preparing new pallet products...');

    const productsToInsert: (typeof palletsProductos.$inferInsert)[] = [
      {
        id: 1,
        fila: 'A',
        posicion: '9.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 2,
        fila: 'A',
        posicion: '10.00',
        codigo: 905037,
        bultos: 72,
        pallets: true,
        vencimiento: new Date('2026-04-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 3,
        fila: 'A',
        posicion: '11.00',
        codigo: 905020,
        bultos: 15,
        pallets: false,
        vencimiento: new Date('2026-09-06'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 4,
        fila: 'A',
        posicion: '11.00',
        codigo: 905018,
        bultos: 15,
        pallets: false,
        vencimiento: new Date('2026-09-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 5,
        fila: 'A',
        posicion: '11.00',
        codigo: 905023,
        bultos: 15,
        pallets: false,
        vencimiento: new Date('2026-11-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 6,
        fila: 'A',
        posicion: '11.00',
        codigo: 905019,
        bultos: 15,
        pallets: false,
        vencimiento: new Date('2026-09-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 7,
        fila: 'A',
        posicion: '12.00',
        codigo: 905037,
        bultos: 72,
        pallets: true,
        vencimiento: new Date('2026-04-08'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 8,
        fila: 'A',
        posicion: '13.00',
        codigo: 2068,
        bultos: 90,
        pallets: true,
        vencimiento: new Date('2026-04-10'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 9,
        fila: 'A',
        posicion: '14.00',
        codigo: 905039,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-02-27'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 10,
        fila: 'A',
        posicion: '15.00',
        codigo: 905028,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-12-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 11,
        fila: 'A',
        posicion: '16.00',
        codigo: 5063,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 12,
        fila: 'A',
        posicion: '17.00',
        codigo: 904561,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2027-07-19'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 13,
        fila: 'A',
        posicion: '18.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 14,
        fila: 'A',
        posicion: '19.00',
        codigo: 905023,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-08-24'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 15,
        fila: 'A',
        posicion: '20.00',
        codigo: 2136,
        bultos: 8,
        pallets: false,
        vencimiento: new Date('2026-05-04'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 16,
        fila: 'A',
        posicion: '20.00',
        codigo: 2140,
        bultos: 8,
        pallets: false,
        vencimiento: new Date('2026-04-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 17,
        fila: 'A',
        posicion: '20.00',
        codigo: 905115,
        bultos: 26,
        pallets: false,
        vencimiento: new Date('2026-03-05'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 18,
        fila: 'A',
        posicion: '20.00',
        codigo: 905116,
        bultos: 13,
        pallets: false,
        vencimiento: new Date('2026-03-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 19,
        fila: 'A',
        posicion: '21.00',
        codigo: 904715,
        bultos: 36,
        pallets: false,
        vencimiento: new Date('2026-03-10'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 20,
        fila: 'A',
        posicion: '23.00',
        codigo: 905018,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-03-21'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 21,
        fila: 'A',
        posicion: '24.00',
        codigo: 904429,
        bultos: 180,
        pallets: true,
        vencimiento: new Date('2026-12-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 22,
        fila: 'A',
        posicion: '25.00',
        codigo: 905020,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-10-16'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 23,
        fila: 'A',
        posicion: '26.00',
        codigo: 905090,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-06-16'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 24,
        fila: 'A',
        posicion: '27.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 25,
        fila: 'A',
        posicion: '28.00',
        codigo: 904733,
        bultos: 72,
        pallets: true,
        vencimiento: new Date('2026-04-07'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 26,
        fila: 'A',
        posicion: '30.00',
        codigo: 904644,
        bultos: 150,
        pallets: true,
        vencimiento: new Date('2026-09-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 27,
        fila: 'A',
        posicion: '32.00',
        codigo: 905014,
        bultos: 90,
        pallets: false,
        vencimiento: new Date('2026-04-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 28,
        fila: 'A',
        posicion: '33.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 29,
        fila: 'A',
        posicion: '34.00',
        codigo: 904643,
        bultos: 150,
        pallets: true,
        vencimiento: new Date('2026-09-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 30,
        fila: 'A',
        posicion: '35.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 31,
        fila: 'A',
        posicion: '36.00',
        codigo: 905027,
        bultos: 54,
        pallets: false,
        vencimiento: new Date('2026-07-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 32,
        fila: 'A',
        posicion: '37.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 33,
        fila: 'A',
        posicion: '38.00',
        codigo: 904643,
        bultos: 150,
        pallets: true,
        vencimiento: new Date('2026-09-19'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 34,
        fila: 'A',
        posicion: '39.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 35,
        fila: 'A',
        posicion: '40.00',
        codigo: 905116,
        bultos: 20,
        pallets: false,
        vencimiento: new Date('2025-01-01'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 36,
        fila: 'A',
        posicion: '41.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 37,
        fila: 'A',
        posicion: '42.00',
        codigo: 904998,
        bultos: 36,
        pallets: false,
        vencimiento: new Date('2025-10-25'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 38,
        fila: 'A',
        posicion: '43.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 39,
        fila: 'A',
        posicion: '44.00',
        codigo: 905028,
        bultos: 36,
        pallets: false,
        vencimiento: new Date('2026-08-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 40,
        fila: 'A',
        posicion: '45.00',
        codigo: 905017,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-04-24'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 41,
        fila: 'A',
        posicion: '46.00',
        codigo: 905019,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2025-12-23'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 42,
        fila: 'A',
        posicion: '47.00',
        codigo: 905014,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-10-03'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 43,
        fila: 'A',
        posicion: '48.00',
        codigo: 905023,
        bultos: 116,
        pallets: false,
        vencimiento: new Date('2026-12-08'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 44,
        fila: 'A',
        posicion: '49.00',
        codigo: 905026,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-10-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 45,
        fila: 'A',
        posicion: '50.00',
        codigo: 904644,
        bultos: 150,
        pallets: true,
        vencimiento: new Date('2026-09-11'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 46,
        fila: 'A',
        posicion: '52.00',
        codigo: 905024,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-01-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 47,
        fila: 'A',
        posicion: '53.00',
        codigo: 905017,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2025-08-24'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 48,
        fila: 'A',
        posicion: '54.00',
        codigo: 905102,
        bultos: 36,
        pallets: false,
        vencimiento: new Date('2025-12-01'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 49,
        fila: 'A',
        posicion: '56.00',
        codigo: 904537,
        bultos: 58,
        pallets: false,
        vencimiento: new Date('2025-09-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 50,
        fila: 'B',
        posicion: '1.00',
        codigo: 905013,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2027-01-05'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 51,
        fila: 'B',
        posicion: '2.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 52,
        fila: 'B',
        posicion: '3.00',
        codigo: 905023,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-12-20'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 53,
        fila: 'B',
        posicion: '4.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 54,
        fila: 'B',
        posicion: '5.00',
        codigo: 905090,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-09-24'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 55,
        fila: 'B',
        posicion: '6.00',
        codigo: 5140,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-04-29'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 56,
        fila: 'B',
        posicion: '7.00',
        codigo: 904714,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-05-08'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 57,
        fila: 'B',
        posicion: '8.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 58,
        fila: 'B',
        posicion: '9.00',
        codigo: 905016,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-09-26'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 59,
        fila: 'B',
        posicion: '10.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 60,
        fila: 'B',
        posicion: '11.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 61,
        fila: 'B',
        posicion: '12.00',
        codigo: 5063,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-05-05'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 62,
        fila: 'B',
        posicion: '13.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 63,
        fila: 'B',
        posicion: '14.00',
        codigo: 904954,
        bultos: 54,
        pallets: true,
        vencimiento: new Date('2026-07-04'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 64,
        fila: 'B',
        posicion: '15.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 65,
        fila: 'B',
        posicion: '16.00',
        codigo: 904954,
        bultos: 54,
        pallets: true,
        vencimiento: new Date('2026-06-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 66,
        fila: 'B',
        posicion: '17.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 67,
        fila: 'B',
        posicion: '18.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 68,
        fila: 'B',
        posicion: '19.00',
        codigo: 905015,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-09-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 69,
        fila: 'B',
        posicion: '20.00',
        codigo: 905038,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 70,
        fila: 'B',
        posicion: '21.00',
        codigo: 905103,
        bultos: 60,
        pallets: true,
        vencimiento: new Date('2026-04-18'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 71,
        fila: 'B',
        posicion: '22.00',
        codigo: 904643,
        bultos: 50,
        pallets: false,
        vencimiento: new Date('2026-10-27'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 72,
        fila: 'B',
        posicion: '22.00',
        codigo: 904644,
        bultos: 150,
        pallets: false,
        vencimiento: new Date('2026-10-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 73,
        fila: 'B',
        posicion: '23.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 74,
        fila: 'B',
        posicion: '24.00',
        codigo: 904713,
        bultos: 72,
        pallets: true,
        vencimiento: new Date('2026-03-27'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 75,
        fila: 'B',
        posicion: '25.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 76,
        fila: 'B',
        posicion: '26.00',
        codigo: 904429,
        bultos: 180,
        pallets: true,
        vencimiento: new Date('2026-10-23'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 77,
        fila: 'B',
        posicion: '27.00',
        codigo: 905026,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-06-23'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 78,
        fila: 'B',
        posicion: '28.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 79,
        fila: 'B',
        posicion: '29.00',
        codigo: 905017,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-02-07'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 80,
        fila: 'B',
        posicion: '30.00',
        codigo: 905109,
        bultos: 60,
        pallets: true,
        vencimiento: new Date('2026-02-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 81,
        fila: 'B',
        posicion: '31.00',
        codigo: 891519,
        bultos: 90,
        pallets: true,
        vencimiento: new Date('2026-02-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 82,
        fila: 'B',
        posicion: '32.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 83,
        fila: 'B',
        posicion: '33.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 84,
        fila: 'B',
        posicion: '34.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-04-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 85,
        fila: 'B',
        posicion: '35.00',
        codigo: 905103,
        bultos: 60,
        pallets: true,
        vencimiento: new Date('2026-06-10'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 86,
        fila: 'B',
        posicion: '36.00',
        codigo: 905050,
        bultos: 60,
        pallets: true,
        vencimiento: new Date('2026-02-07'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 87,
        fila: 'C',
        posicion: '6.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 88,
        fila: 'C',
        posicion: '7.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 89,
        fila: 'C',
        posicion: '8.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 90,
        fila: 'C',
        posicion: '10.00',
        codigo: 5063,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-05-27'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 91,
        fila: 'C',
        posicion: '11.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 92,
        fila: 'C',
        posicion: '12.00',
        codigo: 905019,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-03-18'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 93,
        fila: 'C',
        posicion: '13.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 94,
        fila: 'C',
        posicion: '14.00',
        codigo: 5063,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-05-27'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 95,
        fila: 'C',
        posicion: '15.00',
        codigo: 905103,
        bultos: 60,
        pallets: true,
        vencimiento: new Date('2026-04-18'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 96,
        fila: 'C',
        posicion: '16.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 97,
        fila: 'C',
        posicion: '17.00',
        codigo: 904429,
        bultos: 180,
        pallets: true,
        vencimiento: new Date('2026-12-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 98,
        fila: 'C',
        posicion: '19.00',
        codigo: 905021,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-01-11'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 99,
        fila: 'C',
        posicion: '21.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 100,
        fila: 'C',
        posicion: '22.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 101,
        fila: 'C',
        posicion: '23.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 102,
        fila: 'C',
        posicion: '24.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 103,
        fila: 'C',
        posicion: '25.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 104,
        fila: 'C',
        posicion: '26.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 105,
        fila: 'C',
        posicion: '27.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-13'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 106,
        fila: 'C',
        posicion: '28.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-01'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 107,
        fila: 'C',
        posicion: '29.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 108,
        fila: 'C',
        posicion: '30.00',
        codigo: 905089,
        bultos: 96,
        pallets: false,
        vencimiento: new Date('2026-05-16'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 109,
        fila: 'C',
        posicion: '31.00',
        codigo: 905024,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-01-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 110,
        fila: 'C',
        posicion: '32.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 111,
        fila: 'C',
        posicion: '33.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 112,
        fila: 'C',
        posicion: '34.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 113,
        fila: 'C',
        posicion: '35.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 114,
        fila: 'C',
        posicion: '36.00',
        codigo: 5063,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 115,
        fila: 'C',
        posicion: '37.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 116,
        fila: 'C',
        posicion: '38.00',
        codigo: 904733,
        bultos: 36,
        pallets: false,
        vencimiento: new Date('2026-04-06'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 117,
        fila: 'C',
        posicion: '39.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-13'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 118,
        fila: 'C',
        posicion: '40.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 119,
        fila: 'D',
        posicion: '1.00',
        codigo: 905024,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-02-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 120,
        fila: 'D',
        posicion: '2.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-05-17'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 121,
        fila: 'D',
        posicion: '3.00',
        codigo: 905049,
        bultos: 90,
        pallets: true,
        vencimiento: new Date('2026-02-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 122,
        fila: 'D',
        posicion: '4.00',
        codigo: 5063,
        bultos: 176,
        pallets: true,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 123,
        fila: 'D',
        posicion: '5.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 124,
        fila: 'D',
        posicion: '6.00',
        codigo: 905020,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-05-20'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 125,
        fila: 'D',
        posicion: '7.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 126,
        fila: 'D',
        posicion: '8.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 127,
        fila: 'D',
        posicion: '9.00',
        codigo: 905025,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-04-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 128,
        fila: 'D',
        posicion: '10.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-05-29'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 129,
        fila: 'D',
        posicion: '11.00',
        codigo: 904561,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2027-07-19'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 130,
        fila: 'D',
        posicion: '13.00',
        codigo: 904429,
        bultos: 180,
        pallets: true,
        vencimiento: new Date('2026-12-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 131,
        fila: 'D',
        posicion: '14.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 132,
        fila: 'D',
        posicion: '15.00',
        codigo: 904561,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2027-07-19'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 133,
        fila: 'D',
        posicion: '16.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-05-29'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 134,
        fila: 'D',
        posicion: '17.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-01'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 135,
        fila: 'D',
        posicion: '18.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 136,
        fila: 'D',
        posicion: '19.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 137,
        fila: 'D',
        posicion: '20.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-07-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 138,
        fila: 'D',
        posicion: '21.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 139,
        fila: 'D',
        posicion: '22.00',
        codigo: 905028,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-08-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 140,
        fila: 'D',
        posicion: '24.00',
        codigo: 905028,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-08-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 141,
        fila: 'D',
        posicion: '25.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 142,
        fila: 'D',
        posicion: '26.00',
        codigo: 905013,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-08-18'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 143,
        fila: 'D',
        posicion: '27.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-31'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 144,
        fila: 'D',
        posicion: '28.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-02'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 145,
        fila: 'D',
        posicion: '30.00',
        codigo: 5067,
        bultos: 200,
        pallets: true,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 146,
        fila: 'D',
        posicion: '33.00',
        codigo: 5060,
        bultos: 49,
        pallets: true,
        vencimiento: new Date('2026-08-08'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 147,
        fila: 'D',
        posicion: '34.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2026-03-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 148,
        fila: 'D',
        posicion: '35.00',
        codigo: 905049,
        bultos: 90,
        pallets: true,
        vencimiento: new Date('2026-04-12'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 149,
        fila: 'D',
        posicion: '36.00',
        codigo: 904859,
        bultos: 72,
        pallets: true,
        vencimiento: new Date('2026-03-19'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 150,
        fila: 'E',
        posicion: '0.30',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 151,
        fila: 'E',
        posicion: '2.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 152,
        fila: 'E',
        posicion: '6.00',
        codigo: 891519,
        bultos: 90,
        pallets: true,
        vencimiento: new Date('2026-02-22'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 153,
        fila: 'E',
        posicion: '7.00',
        codigo: 905049,
        bultos: 90,
        pallets: true,
        vencimiento: new Date('2026-02-16'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 154,
        fila: 'E',
        posicion: '12.00',
        codigo: 905018,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-08-29'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 155,
        fila: 'E',
        posicion: '13.00',
        codigo: 904429,
        bultos: 180,
        pallets: true,
        vencimiento: new Date('2026-12-26'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 156,
        fila: 'E',
        posicion: '15.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 157,
        fila: 'E',
        posicion: '16.00',
        codigo: 904912,
        bultos: 90,
        pallets: false,
        vencimiento: new Date('2025-05-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 158,
        fila: 'E',
        posicion: '18.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-17'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 159,
        fila: 'E',
        posicion: '19.00',
        codigo: 905028,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-07-01'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 160,
        fila: 'E',
        posicion: '20.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 161,
        fila: 'E',
        posicion: '21.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 162,
        fila: 'E',
        posicion: '22.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 163,
        fila: 'E',
        posicion: '23.00',
        codigo: 905018,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-03-09'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 164,
        fila: 'E',
        posicion: '25.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-14'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 165,
        fila: 'E',
        posicion: '27.00',
        codigo: 905029,
        bultos: 50,
        pallets: true,
        vencimiento: new Date('2025-07-13'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 166,
        fila: 'E',
        posicion: '29.00',
        codigo: 905036,
        bultos: 140,
        pallets: true,
        vencimiento: new Date('2025-07-13'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 167,
        fila: 'E',
        posicion: '31.00',
        codigo: 905014,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-04-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 168,
        fila: 'F',
        posicion: '4.00',
        codigo: 905024,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2025-12-01'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 169,
        fila: 'F',
        posicion: '6.00',
        codigo: 905090,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-05-25'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 170,
        fila: 'F',
        posicion: '8.00',
        codigo: 905023,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-06-25'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 171,
        fila: 'F',
        posicion: '10.00',
        codigo: 905023,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-07-21'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 172,
        fila: 'F',
        posicion: '12.00',
        codigo: 905016,
        bultos: 162,
        pallets: true,
        vencimiento: new Date('2026-05-05'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 173,
        fila: 'S',
        posicion: '1.00',
        codigo: 905123,
        bultos: 39,
        pallets: false,
        vencimiento: new Date('2026-04-08'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 174,
        fila: 'S',
        posicion: '2.00',
        codigo: 905058,
        bultos: 13,
        pallets: false,
        vencimiento: new Date('2025-08-15'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 175,
        fila: 'S',
        posicion: '3.00',
        codigo: 5140,
        bultos: 48,
        pallets: false,
        vencimiento: new Date('2026-03-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 176,
        fila: 'S',
        posicion: '4.00',
        codigo: 905058,
        bultos: 18,
        pallets: false,
        vencimiento: new Date('2025-10-30'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 178,
        fila: 'S',
        posicion: '9.00',
        codigo: 5067,
        bultos: 50,
        pallets: false,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 179,
        fila: 'S',
        posicion: '10.00',
        codigo: 5067,
        bultos: 50,
        pallets: false,
        vencimiento: new Date('2026-05-28'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
      {
        id: 180,
        fila: 'S',
        posicion: '19.00',
        codigo: 5067,
        bultos: 10,
        pallets: false,
        vencimiento: new Date('2026-02-11'),
        userId: 1,
        idEmpresa: 1,
        observaciones: null,
      },
    ];

    // 4. Insertar productos de pallet
    console.log(`➕ Inserting ${productsToInsert.length} new pallet products...`);
    await db.insert(palletsProductos).values(productsToInsert);
    // Después de insertar IDs explícitos, actualiza la secuencia al MAX(id) + 1
    await db.execute(
      sql`SELECT setval('pallets_productos_id_seq', (SELECT MAX(id) FROM pallets_productos));`,
    );
    console.log('✅ Pallet products seeded successfully!');
  } catch (error) {
    console.error('❌ Error seeding pallet products:', error);
    process.exit(1);
  }
}

async function seed() {
  // Asegurar que la empresa base exista antes de intentar insertar posiciones y productos
  await seedEmpresas(); 
  await seedPalletPositions();
  await seedPalletProducts(); 
  console.log('🎉 All pallet seeding complete!');
}

// Ejecutar la función principal
seed().finally(async () => {
  await pool.end();
  console.log('👋 Seeding connection closed.');
});